name: 'Compile and upload document'
on: [push]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./ci
          push: true
          tags: ghcr.io/icepack/dual-problems:latest

  build_latex:
    runs-on: ubuntu-latest
    needs: build_docker_image
    container:
      image: ghcr.io/icepack/dual-problems:latest
      options: --user root
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Install Python package
        run: pip install --editable demos/dualform
      - name: Compile TeX document
        run: make
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: dual-problems
          path: dual-problems.pdf
