name: 'Compile and upload document'
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: docker.io/firedrakeproject/firedrake-vanilla:2023-11
      options: --user root
    steps:
      - name: Activate Firedrake virtual environment
        run: |
          . /home/firedrake/firedrake/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          apt update
          apt install -yq patchelf texlive texlive-fonts-extra
          pip install netCDF4
          pip install git+https://github.com/firedrakeproject/irksome.git
          pip install git+https://github.com/icepack/Trilinos.git
          pip install git+https://github.com/icepack/pyrol.git
          pip install git+https://github.com/icepack/icepack.git
      - name: Check out git repository
        uses: actions/checkout@v3
      - name: Install Python package
        run: pip install --editable demos/dualform
      - name: Compile TeX document
        env:
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
        run: make
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: dual-problems
          path: dual-problems.pdf
